M48
; DRILL file {KiCad 8.0.8} date 2025-01-29T17:43:00+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-29T17:43:00+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X147.11Y-47.432
X152.89Y-47.432
T2
X161.019Y-125.64
X162.035Y-120.56
X163.051Y-125.64
M30
