M48
; DRILL file {KiCad 9.0.2} date 2025-05-11T21:09:18+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-11T21:09:18+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X144.61Y-61.849
X150.39Y-61.849
T2
X161.5Y-99.934
X162.516Y-105.014
X163.532Y-99.934
M30
